# Generated by Django 4.2.17 on 2025-07-20 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0004_users_is_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="verification_code",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                validators=[django.core.validators.MinLengthValidator(50)],
                verbose_name="verification_code",
            ),
        ),
    ]
