# Generated by Django 4.2.17 on 2025-07-20 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0005_alter_users_verification_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="balance",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="balance",
            ),
        ),
    ]
