# Generated by Django 4.2.17 on 2025-07-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_alter_users_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_created=True, verbose_name='created_at'),
        ),
    ]
